### ISSUE TITLE
Tracks as Points

### ISSUE THREAD

**Issue by pjdufour** [GFDRR/osm-extract#2]
Shapefile as tracks is points rather than lines.  Not sure why the command is so much different than the paths command, which generates lines.

https://github.com/GFDRR/osm-extract/blob/master/Makefile#L104

**Comment by ingenieroariel** [comment]
Fixed in https://github.com/GFDRR/osm-extract/commit/8416fedb760a71ecc7e2c505fcbe04829dc07d4c#diff-b67911656ef5d18c4ae36cb6741b7965R105
